Let's incluce README.md in a topic directory, to allow more existing in one image
We also don't need to include README.md in the root, just help.1 should be enough.

diff --git a/4.1/test/run b/4.1/test/run
--- a/4.1/test/run
+++ b/4.1/test/run
@@ -48,27 +48,26 @@ function run {
     return $res
 }
 
-run_doc_check() {
+run_doc_test() {
   local tmpdir=$(mktemp -d)
+  local f
   echo "  Testing documentation in the container image"
   # Extract the help files from the container
-  for f in help.md help.1 ; do
-    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/${f}
+  for f in /usr/share/container-scripts/ror/README.md help.1 ; do
+    docker run --rm ${IMAGE_NAME} /bin/bash -c "cat /${f}" >${tmpdir}/$(basename ${f})
+    # Check whether the files include some important information
+    for term in nodejs layered ; do
+      if ! cat ${tmpdir}/$(basename ${f}) | grep -q -e "${term}" ; then
+        echo "ERROR: File /${f} does not include '${term}'."
+        return 1
+      fi
+    done
   done
   # Check whether the files use the correct format
   if ! file ${tmpdir}/help.1 | grep -q roff ; then
     echo "ERROR: /help.1 is not in troff or groff format"
     return 1
   fi
-  # Check whether the files include some important information
-  for term in nodejs layered ; do
-    for f in help.md help.1 ; do
-      if ! cat ${tmpdir}/${f} | grep -q -e "${term}" ; then
-        echo "ERROR: File /${f} does not include '${term}'."
-        return 1
-      fi
-    done
-  done
   echo "  Success!"
   echo
 }
@@ -107,7 +106,7 @@ rm_container test_welcome_page
 CONTAINER_ARGS="bash -c 'rails new myapp --skip-bundle && cd myapp && sed -i -e \"s/\(gem.*web-console\)/#\1/\" Gemfile && bundle --local && rake assets:precompile'"
 run "docker run --rm $IMAGE_NAME $CONTAINER_ARGS"
 
-run_doc_check
+run_doc_test
 update_overall $?
 
 popd > /dev/null
